// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'managePanel': string;
  'managePanelItems': string;
  'profilesContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
