// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'headerContainer': string;
  'info': string;
  'infoText': string;
  'infoValue': string;
  'infoValueLoaded': string;
  'mottoContainer': string;
  'mottoText': string;
  'mottoTextLoaded': string;
  'textCred': string;
  'textMan': string;
}
declare var cssExports: CssExports;
export = cssExports;
