// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'exit-splash': string;
  'headerContainer': string;
  'info': string;
  'infoText': string;
  'infoValue': string;
  'logoText': string;
  'motto': string;
  'textCred': string;
  'textMan': string;
}
declare var cssExports: CssExports;
export = cssExports;
